apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
spec:
  replicas: 1
  selector:
    app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
        openai/do-not-drain: "true"
    spec:
      containers:
      - name: autoscaler
        image: wbuchwalter/kubernetes-acs-engine-autoscaler
        env:
        - name: AZURE_SP_APP_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-app-id
        - name: AZURE_SP_SECRET
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-secret
        - name: AZURE_SP_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-tenant-id    
        - name: KUBECONFIG_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: kubeconfig-private-key
        - name: CLIENT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: client-private-key   
        command:
            - python
            - main.py
            - --resource-group 
            - <your-group-name>
            - --acs-deployment
            - <your-deployment-name>
            - -vvv
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: Default  # Don't use cluster DNS.
